/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/rightcave.ts" />
/// <reference path="../scenes/leftcave.ts" />
/// <reference path="../scenes/intro.ts" />
/// <reference path="../scenes/LScene.ts" />
/// <reference path="../scenes/RScene.ts" />
/// <reference path="../scenes/LLScene.ts" />
/// <reference path="../scenes/LRScene.ts" />
/// <reference path="../scenes/RLScene.ts" />
/// <reference path="../scenes/RRScene.ts" />
/// <reference path="../scenes/LLLScene.ts" />
/// <reference path="../scenes/LLRScene.ts" />
/// <reference path="../scenes/LRLScene.ts" />
/// <reference path="../scenes/LRRScene.ts" />
/// <reference path="../scenes/RLLScene.ts" />
/// <reference path="../scenes/RLRScene.ts" />
/// <reference path="../scenes/RRLScene.ts" />
/// <reference path="../scenes/RRRScene.ts" /> 
//# sourceMappingURL=_reference.js.map